### ISSUE TITLE
13:21:00 ERROR napari.manifest -> 'napari-cellplato' could not be imported: Could not find file 'napari.yaml' in module 'napari_cellplato'

### ISSUE THREAD

**Issue by fabricesenger** [Michael-shannon/napari-cellplato#1]
hello

 i tried to instal the napari plugin and cloned it from git the install worked 👍 "Successfully installed napari-cellplato-0.0.1"
but when i launch my napari i get the mentionned error...

besides that i would like to use napari as i have btrack installed and working

thus it would be possible to make some tests on my monolayer movies

Thank you for your support,

Fabrice.

**Comment by fabricesenger** [comment]
Dear Michael,
on this issue i'm happily trying out the different napari.yaml files in the different napari-cellplato folders ... No succes so far.
The plugin pops up in the plugin list but in the submenu i only get example widgets 
Fabrice.

**Comment by Michael-shannon** [comment]
Ah I am sorry to tell you that the Napari plugin is not made yet.

I hope to get to it at some point in the future but its all jupyter based at the moment! You can easily view tracks in Napari though, using the btrack viewer or just the regular base Napari by importing tracks as a layer.
